'use strict';

// ---- Rules, shared state and UI ----------------------------------------------
const COMBO_WINDOW=520,REFEREE_SIGNAL_DURATION=3000,REFEREE_MOVE_DURATION=400,REFEREE_HALT_DURATION=350,STRIP={left:80,right:1120,y:438},SAVE_KEY='sabreTournamentV1';
const GAME={MENU:'menu',UNGARD:'ungard',READY:'ready',FENCE:'fence',HALT:'halt',BREAK:'break',OVER:'over',PAUSED:'paused'};
const STATE={GUARD:'guard',ADVANCE:'advance',RETREAT:'retreat',ATTACK:'attack',LUNGE:'lunge',PARRY:'parry',RIPOSTE:'riposte',DUCK:'duck',HIT:'hit',RECOVER:'recover'};
const REF={IDLE:'idle',UNGARD:'ungard',READY:'ready',FENCE:'fence',STOP:'stop',PLAYER_POINT:'player_point',COMPUTER_POINT:'computer_point',PAUSE:'pause',MATCH_END:'match_end'};
const RESULT={MISS:'MISS',OUT_OF_RANGE:'OUT_OF_RANGE',PARRIED:'PARRIED',TOUCH:'TOUCH'};
const DIFFICULTIES={easy:{reaction:.49,skill:.27,aggression:.62,mistake:.30},normal:{reaction:.30,skill:.54,aggression:.50,mistake:.16},hard:{reaction:.18,skill:.76,aggression:.48,mistake:.09},expert:{reaction:.13,skill:.88,aggression:.45,mistake:.07}};
const STYLES=['BALANCED','AGGRESSIVE','DEFENSIVE','COUNTERATTACKER','DISTANCE'];
const NAMES=['ALEX','JORDAN','CHRIS','MORGAN','CASEY','TAYLOR','SAM','JAMIE','DREW','QUINN','DEVON','SKYE','ARI','REMY','SASHA','NICO','ELI','ROBIN','PARKER','BLAIR','CAMERON','DANA','EMERY','FINN','HARPER','JULES','KAI','LOGAN','MICA','NOEL','RILEY'];
const $=s=>document.querySelector(s),canvas=$('#gameCanvas'),ctx=canvas.getContext('2d');
const ui={menu:$('#menu'),ann:$('#announcement'),annTop:$('#announcementTop'),annMain:$('#announcementMain'),annSub:$('#announcementSub'),toast:$('#toast'),ps:$('#playerScore'),cs:$('#computerScore'),pName:$('#playerNameLabel'),cName:$('#computerNameLabel'),round:$('#roundLabel'),distance:$('#distanceLabel'),stamina:$('#staminaFill'),combo:$('#comboLabel'),pause:$('#pauseOverlay'),match:$('#matchOverlay'),result:$('#matchResult'),summary:$('#matchSummary'),refPanel:$('#refereePanel'),refDecision:$('#refereeDecision'),refReason:$('#refereeReason'),refStatus:$('#refereeStatus'),ribbon:$('#tournamentRibbon'),stage:$('#stageLabel'),piste:$('#pisteLabel'),breakOverlay:$('#breakOverlay')};
let gameState=GAME.MENU,previousState=GAME.MENU,lastTime=0,sequenceTimer=0,pointTimer=0,slowMotion=1,shake=0,particles=[],toastTimer=0,currentDecision=null,inputHistory=[],soundOn=true,musicOn=false,musicTimer=null,instructionsPaused=false,restartPaused=false;
let bout={mode:'quick',target:5,stage:'QUICK BOUT',opponent:null,breakTaken:false,point:1};
const referee={state:REF.IDLE,stateTime:0,signalStartTime:null};
const keys=new Set(),pressed=new Set();
function makeFencer(side){return {side,x:side==='player'?330:870,facing:side==='player'?1:-1,state:STATE.GUARD,stateTime:0,stamina:100,score:0,hitResolved:false,parrySuccess:false,riposteWindow:0,priorityTime:Infinity,aiTimer:0,aiIntent:'idle'};}
let player=makeFencer('player'),computer=makeFencer('computer');

// ---- Input -------------------------------------------------------------------
const movement={left:['KeyA','ArrowLeft'],right:['KeyD','ArrowRight'],burst:['KeyW','ArrowUp'],duck:['KeyS','ArrowDown']};
const down=n=>movement[n].some(k=>keys.has(k));
addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space'].includes(e.code))e.preventDefault();if(gameState===GAME.BREAK&&(e.code==='Space'||e.code==='Enter')&&!e.repeat){e.preventDefault();endBreak(true);return;}if(!keys.has(e.code))pressed.add(e.code);keys.add(e.code);if(e.code==='KeyP'&&!e.repeat)togglePause();if(e.code==='KeyR'&&!e.repeat)requestRestart();if(e.code==='Escape')closeTopModal();});
addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>keys.clear());
function recordInput(code){inputHistory.push({code,t:performance.now()});inputHistory=inputHistory.filter(i=>performance.now()-i.t<COMBO_WINDOW*2);}
function hasCombo(seq){let at=0,start=0;for(const i of inputHistory)if(i.code===seq[at]){if(!at)start=i.t;if(++at===seq.length)return i.t-start<=COMBO_WINDOW;}return false;}

// ---- Bout flow / authoritative scoring ---------------------------------------
function configureBout(config){bout={breakTaken:false,point:1,...config};difficulty=config.difficulty||difficulty||'normal';ui.menu.classList.add('hidden');hideScreens();ui.match.classList.add('hidden');ui.breakOverlay.classList.add('hidden');ui.ribbon.classList.toggle('hidden',config.mode!=='tournament');ui.stage.textContent=config.stage||config.mode.toUpperCase();ui.piste.textContent=config.meta||'PISTE 3';ui.pName.textContent=config.playerName||Tournament.data?.playerName||'PLAYER';ui.cName.textContent=config.opponent?.name||'COMPUTER';resetBout();}
function resetBout(){player=makeFencer('player');computer=makeFencer('computer');bout.point=1;bout.breakTaken=false;particles=[];currentDecision=null;updateScore();beginPoint();}
function resetPositions(){Object.assign(player,makeFencer('player'),{score:player.score});Object.assign(computer,makeFencer('computer'),{score:computer.score});}
function setRef(state){referee.state=state;referee.stateTime=0;ui.refStatus.textContent=`REFEREE · ${state.replace('_',' ').toUpperCase()}`;}
function beginPoint(){resetPositions();currentDecision=null;ui.refPanel.classList.add('hidden');gameState=GAME.UNGARD;sequenceTimer=0;setRef(REF.UNGARD);const matchPoint=player.score===bout.target-1||computer.score===bout.target-1;showAnnouncement(matchPoint?'MATCH POINT':bout.stage, 'UNGARD',matchPoint&&player.score===computer.score?'NEXT TOUCH WINS':'REFEREE CALL');tone(220,.08);}
function updateSequence(dt){sequenceTimer+=dt;if(gameState===GAME.UNGARD&&sequenceTimer>1){gameState=GAME.READY;sequenceTimer=0;setRef(REF.READY);showAnnouncement(bout.stage,'READY','REFEREE CALL');tone(330,.08);}else if(gameState===GAME.READY&&sequenceTimer>.9){gameState=GAME.FENCE;sequenceTimer=0;setRef(REF.FENCE);showAnnouncement('','FENCE!','');tone(660,.13);setTimeout(()=>{if(gameState===GAME.FENCE){ui.ann.classList.add('hidden');setRef(REF.IDLE);}},520);}}
function scoreTouch(winner,reason,detail){return refereeDecision({type:RESULT.TOUCH,scorer:winner.side,reason,detail:detail||reason});}
function refereeDecision(result){if(gameState!==GAME.FENCE||result.type!==RESULT.TOUCH)return result;currentDecision={...result,signalStarted:false,scoreApplied:false};gameState=GAME.HALT;pointTimer=0;slowMotion=.28;shake=10;referee.signalStartTime=null;setRef(REF.STOP);showAnnouncement('REFEREE','HALT!','ANALYZING PHRASE');ui.refPanel.classList.add('hidden');tone(180,.12);return result;}
function startSignal(){if(currentDecision.signalStarted)return;currentDecision.signalStarted=true;referee.signalStartTime=performance.now();ui.ann.classList.add('hidden');ui.refPanel.classList.remove('hidden');ui.refDecision.textContent=`TOUCH — ${currentDecision.scorer.toUpperCase()}`;ui.refReason.textContent=currentDecision.reason;setRef(currentDecision.scorer==='player'?REF.PLAYER_POINT:REF.COMPUTER_POINT);tone(currentDecision.scorer==='player'?880:150,.18);}
function applyScore(){if(currentDecision.scoreApplied)return;currentDecision.scoreApplied=true;const winner=currentDecision.scorer==='player'?player:computer;winner.score++;if(currentDecision.scorer==='player')Tournament.trackTouch(currentDecision.reason);spawnSparks(winner===player?computer.x:player.x,320,winner===player?'#57e3ff':'#ff6372',26);flashToast(`${currentDecision.scorer.toUpperCase()} +1 · ${currentDecision.detail}`);updateScore();saveTournament();}
function updateHalt(dt){pointTimer+=dt;slowMotion=Math.min(1,slowMotion+dt*1.8);if(pointTimer>=REFEREE_HALT_DURATION/1000)startSignal();if(!currentDecision.signalStarted)return;const elapsed=performance.now()-referee.signalStartTime;if(elapsed>=REFEREE_MOVE_DURATION+REFEREE_SIGNAL_DURATION)applyScore();if(!currentDecision.scoreApplied||elapsed<REFEREE_MOVE_DURATION+REFEREE_SIGNAL_DURATION+500)return;if(player.score>=bout.target||computer.score>=bout.target){finishBout();return;}if(bout.mode==='tournament'&&bout.tournamentKind==='de'&&!bout.breakTaken&&(player.score>=8||computer.score>=8)){startBreak();return;}bout.point++;beginPoint();}
function finishBout(){gameState=GAME.OVER;setRef(REF.MATCH_END);ui.refPanel.classList.add('hidden');const won=player.score>computer.score;if(bout.mode==='tournament'){Tournament.completePlayerBout(won,player.score,computer.score);return;}ui.match.classList.remove('hidden');$('#matchEyebrow').textContent=bout.mode==='practice'?'TRAINING':'REFEREE’S FINAL DECISION';ui.result.textContent=won?'YOU WIN!':'COMPUTER WINS!';ui.summary.textContent=`FINAL SCORE ${player.score} — ${computer.score}`;tone(won?960:130,.35);}
function startBreak(){bout.breakTaken=true;gameState=GAME.BREAK;ui.refPanel.classList.add('hidden');ui.breakOverlay.classList.remove('hidden');$('#breakPlayerName').textContent=ui.pName.textContent;$('#breakOpponentName').textContent=ui.cName.textContent;$('#breakPlayerScore').textContent=player.score;$('#breakOpponentScore').textContent=computer.score;$('#breakTimer').textContent='1:00';bout.breakEndsAt=Date.now()+60000;clearInterval(bout.breakInterval);bout.breakInterval=setInterval(updateBreakClock,200);tone(260,.35);}
function updateBreakClock(){if(gameState!==GAME.BREAK){clearInterval(bout.breakInterval);return;}const remaining=Math.max(0,Math.ceil((bout.breakEndsAt-Date.now())/1000));$('#breakTimer').textContent=`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`;if(remaining<=0)endBreak(false);}
function endBreak(skipped){if(gameState!==GAME.BREAK)return;clearInterval(bout.breakInterval);ui.breakOverlay.classList.add('hidden');bout.point++;resetPositions();currentDecision=null;gameState=GAME.READY;sequenceTimer=0;setRef(REF.READY);showAnnouncement('BREAK OVER','READY',skipped?'BREAK SKIPPED · SCORE PRESERVED':'SCORE PRESERVED');tone(420,.12);}
function updateScore(){ui.ps.textContent=player.score;ui.cs.textContent=computer.score;ui.round.textContent=bout.mode==='practice'?`PRACTICE · TOUCHES ${player.score+computer.score}`:`FIRST TO ${bout.target}`;}

// ---- Fencing actions and collision -------------------------------------------
function canAct(f){return [STATE.GUARD,STATE.ADVANCE,STATE.RETREAT,STATE.DUCK].includes(f.state);}
function beginAction(f,state){if(!canAct(f))return false;const cost=state===STATE.LUNGE?24:state===STATE.ATTACK?11:state===STATE.PARRY?8:13;if(f.stamina<cost)return false;f.stamina-=cost;f.state=state;f.stateTime=0;f.hitResolved=false;if([STATE.ATTACK,STATE.LUNGE,STATE.RIPOSTE].includes(state))f.priorityTime=performance.now();return true;}
function attack(f,type=STATE.ATTACK){if(beginAction(f,type)){tone(300,.04);if(f===player){Tournament.stat(type===STATE.LUNGE?'lunges':'attacks');flashToast(type===STATE.LUNGE?'LUNGE!':'ATTACK!');}}}
function parry(f){if(beginAction(f,STATE.PARRY)){tone(520,.03);if(f===player){Tournament.stat('parries');flashToast('PARRY!');}}}
function riposte(f){if(f.riposteWindow>0&&canAct(f)){beginAction(f,STATE.RIPOSTE);f.priorityTime=performance.now()-1000;if(f===player){Tournament.stat('ripostes');flashToast('RIPOSTE!');}}else if(f===player)flashToast('NO RIPOSTE WINDOW');}
function feint(f){if([STATE.ATTACK,STATE.LUNGE].includes(f.state)&&f.stateTime<.18){f.state=STATE.RECOVER;f.stateTime=0;f.priorityTime=Infinity;if(f===player)flashToast('FEINT');return true;}return false;}
function actionPhase(f){const t=f.stateTime;if(f.state===STATE.ATTACK)return t<.13?'startup':t<.25?'active':t<.48?'recovery':'done';if(f.state===STATE.LUNGE)return t<.16?'startup':t<.34?'active':t<.65?'recovery':'done';if(f.state===STATE.RIPOSTE)return t<.07?'startup':t<.22?'active':t<.42?'recovery':'done';if(f.state===STATE.PARRY)return t<.08?'startup':t<.27?'active':t<.45?'recovery':'done';return '';}
function blade(f){const phase=actionPhase(f),active=phase==='active'&&[STATE.ATTACK,STATE.LUNGE,STATE.RIPOSTE].includes(f.state),parrying=f.state===STATE.PARRY&&phase==='active',duck=f.state===STATE.DUCK,handX=f.x+f.facing*20,handY=duck?337:300,reach=active?(f.state===STATE.LUNGE?150:132):parrying?84:92,angle=parrying?-f.facing*1.05:active?-.04*f.facing:-.28*f.facing;return{x1:handX,y1:handY,x2:handX+Math.cos(angle)*reach*f.facing,y2:handY+Math.sin(angle)*reach};}
function targets(f){const d=f.state===STATE.DUCK?25:0;return[{x:f.x-18,y:245+d,w:36,h:55},{x:f.x-30,y:300+d,w:60,h:100},{x:f.x-42,y:305+d,w:84,h:24}];}
function lineRect(l,r){for(let i=0;i<=14;i++){const t=i/14,x=l.x1+(l.x2-l.x1)*t,y=l.y1+(l.y2-l.y1)*t;if(x>=r.x&&x<=r.x+r.w&&y>=r.y&&y<=r.y+r.h)return true;}return false;}
function bladesCross(a,b){const A=blade(a),B=blade(b);return Math.abs(A.x2-B.x2)<58&&Math.abs(A.y2-B.y2)<70;}
function resolveCombat(a,d){if(a.hitResolved||actionPhase(a)!=='active')return null;a.hitResolved=true;if(d.state===STATE.PARRY&&actionPhase(d)==='active'&&bladesCross(a,d)){a.state=STATE.RECOVER;a.stateTime=0;d.riposteWindow=.62;d.priorityTime=performance.now()-1200;spawnSparks((a.x+d.x)/2,290,'#fff4bd',14);flashToast(d===player?'PARRIED — RIPOSTE NOW!':'COMPUTER PARRY');tone(920,.1);return{type:RESULT.PARRIED};}const hit=targets(d).some(r=>lineRect(blade(a),r));if(!hit){const far=Math.abs(a.x-d.x)>260;if(a===player)flashToast(far?'OUT OF RANGE':'MISS');return{type:far?RESULT.OUT_OF_RANGE:RESULT.MISS};}const other=[STATE.ATTACK,STATE.LUNGE,STATE.RIPOSTE].includes(d.state)&&actionPhase(d)==='active';if(other&&!d.hitResolved){const winner=a.priorityTime<=d.priorityTime?a:d;a.hitResolved=d.hitResolved=true;return scoreTouch(winner,winner.state===STATE.RIPOSTE?'RIPOSTE':'PRIORITY',`Double attack — ${winner.side} priority`);}return scoreTouch(a,a.state===STATE.RIPOSTE?'RIPOSTE':a.state===STATE.LUNGE?'LUNGE ATTACK':'ATTACK','Clean target hit');}
function updateFencer(f,dt){f.stateTime+=dt;f.riposteWindow=Math.max(0,f.riposteWindow-dt);f.stamina=Math.min(100,f.stamina+dt*(f.state===STATE.GUARD?20:9));if(f.state===STATE.LUNGE&&f.stateTime<.32)f.x+=f.facing*390*dt;if(f.state===STATE.RIPOSTE&&f.stateTime<.2)f.x+=f.facing*230*dt;if(actionPhase(f)==='done'||f.state===STATE.RECOVER&&f.stateTime>.25){f.state=STATE.GUARD;f.stateTime=0;f.priorityTime=Infinity;}f.x=Math.max(STRIP.left+45,Math.min(STRIP.right-45,f.x));}
function handlePlayer(dt){if(pressed.has('KeyJ')){recordInput('J');attack(player,hasCombo(['D','SPACE','J'])?STATE.LUNGE:STATE.ATTACK);}if(pressed.has('Space')){recordInput('SPACE');attack(player,STATE.LUNGE);}if(pressed.has('KeyK')){recordInput('K');if(!feint(player))parry(player);}if(pressed.has('KeyL')){recordInput('L');riposte(player);}if(pressed.has('KeyD')||pressed.has('ArrowRight'))recordInput('D');if(canAct(player)){let dir=down('right')-down('left'),speed=190;if(down('burst')&&player.stamina>3){speed=285;player.stamina-=12*dt;}if(down('duck'))player.state=STATE.DUCK;else if(dir){player.state=dir>0?STATE.ADVANCE:STATE.RETREAT;player.x+=dir*speed*dt;}else player.state=STATE.GUARD;}}

// ---- Personality-driven AI ----------------------------------------------------
let difficulty='normal';
function updateAI(dt){const cfg=DIFFICULTIES[difficulty],style=bout.opponent?.style||'BALANCED',dist=computer.x-player.x;computer.aiTimer-=dt;const aggression=cfg.aggression+(style==='AGGRESSIVE'?.25:style==='DEFENSIVE'?-.2:0),defense=cfg.skill+((style==='DEFENSIVE'||style==='COUNTERATTACKER')?.13:0);if((player.state===STATE.ATTACK||player.state===STATE.LUNGE)&&computer.aiTimer<=0){computer.aiTimer=cfg.reaction;if(Math.random()<defense*(dist<310?1:.3))computer.aiIntent=Math.random()<defense?'parry':'retreat';}if(computer.riposteWindow>0&&canAct(computer)){riposte(computer);computer.aiIntent='recover';return;}if(computer.aiTimer<=0&&canAct(computer)){computer.aiTimer=.18+Math.random()*.35;if(Math.random()<cfg.mistake)computer.aiIntent=Math.random()<.5?'attack':'approach';else if(computer.aiIntent==='parry'){parry(computer);computer.aiIntent='recover';return;}else if(dist>370)computer.aiIntent=style==='DISTANCE'&&dist<430?'idle':'approach';else if(dist<155)computer.aiIntent=Math.random()<.72?'retreat':'parry';else if(dist<290&&Math.random()<aggression)computer.aiIntent=Math.random()<.48?'lunge':'attack';else computer.aiIntent=Math.random()<(style==='COUNTERATTACKER'?.65:.42)?'retreat':'approach';}if(canAct(computer)){if(computer.aiIntent==='attack'){attack(computer);computer.aiIntent='recover';}else if(computer.aiIntent==='lunge'){attack(computer,STATE.LUNGE);computer.aiIntent='recover';}else{const dir=computer.aiIntent==='approach'?-1:computer.aiIntent==='retreat'?1:0;computer.x+=dir*(difficulty==='expert'?185:difficulty==='hard'?175:145)*dt;computer.state=dir<0?STATE.ADVANCE:dir>0?STATE.RETREAT:STATE.GUARD;}}}

// ---- Tournament system --------------------------------------------------------
const Tournament={data:null,
  new(size,name){const list=[this.fencer('player',name||'RAY',70,'BALANCED',true)];for(let i=0;i<size-1;i++)list.push(this.fencer(`ai${i}`,NAMES[i],38+Math.floor(Math.random()*58),STYLES[i%STYLES.length],false));for(let i=list.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]];}const pools=[];for(let i=0;i<size/4;i++)pools.push({name:String.fromCharCode(65+i),fencers:list.slice(i*4,i*4+4)});this.data={size,playerName:(name||'RAY').toUpperCase(),fencers:list,pools,phase:'pools',playerSchedule:[],history:[],stats:{poolWins:0,poolLosses:0,deWins:0,deLosses:0,touchesScored:0,touchesReceived:0,attacks:0,lunges:0,parries:0,ripostes:0,successfulTouches:0},ranking:[],deEntrants:[],deRounds:[],currentRound:null};this.buildPools();this.save();this.showPools();},
  fencer(id,name,skill,style,isPlayer){return{id,name:name.toUpperCase(),skill,style,isPlayer,wins:0,losses:0,ts:0,tr:0,seed:0};},
  buildPools(){for(const pool of this.data.pools){for(let i=0;i<4;i++)for(let j=i+1;j<4;j++){const a=pool.fencers[i],b=pool.fencers[j];if(a.isPlayer||b.isPlayer)this.data.playerSchedule.push({pool:pool.name,opponentId:(a.isPlayer?b:a).id,status:'UPCOMING'});else this.applyResult(a,b,...this.simulate(a,b,5));}}},
  simulate(a,b,target){const delta=(a.skill-b.skill)/17+(a.style==='AGGRESSIVE'?.12:0)-(b.style==='AGGRESSIVE'?.12:0),chance=1/(1+Math.exp(-delta));const aWins=Math.random()<chance,winner=aWins?a:b,loser=aWins?b:a,loseScore=Math.max(0,Math.min(target-1,Math.round(target-2+(Math.random()-.5)*3+(loser.skill-winner.skill)/25)));return aWins?[target,loseScore]:[loseScore,target];},
  applyResult(a,b,as,bs){a.ts+=as;a.tr+=bs;b.ts+=bs;b.tr+=as;if(as>bs){a.wins++;b.losses++;}else{b.wins++;a.losses++;}},
  nextPoolBout(){return this.data.playerSchedule.find(x=>x.status==='UPCOMING');},
  startNextPool(){const item=this.nextPoolBout();if(!item)return this.finishPools();item.status='NEXT';const opp=this.find(item.opponentId);configureBout({mode:'tournament',target:5,stage:`POOL ${item.pool}`,meta:`PISTE 3 · BOUT ${this.data.playerSchedule.indexOf(item)+1}`,playerName:this.data.playerName,opponent:opp,difficulty:this.level(opp.skill),tournamentKind:'pool',scheduleItem:item});},
  completePlayerBout(won,ps,cs){const opp=bout.opponent;this.applyResult(this.player(),opp,ps,cs);this.data.stats.touchesScored+=ps;this.data.stats.touchesReceived+=cs;const record={stage:bout.stage,opponent:opp.name,won,playerScore:ps,opponentScore:cs};this.data.history.push(record);if(bout.tournamentKind==='pool'){const item=this.data.playerSchedule.find(x=>x.status==='NEXT');item.status='DONE';item.score=`${ps} — ${cs}`;item.won=won;this.data.stats[won?'poolWins':'poolLosses']++;this.save();this.showPools();}else{this.data.stats[won?'deWins':'deLosses']++;this.resolveDERound(won,record);}},
  finishPools(){this.data.ranking=[...this.data.fencers].sort((a,b)=>b.wins-a.wins||(b.ts-b.tr)-(a.ts-a.tr)||b.ts-a.ts||a.id.localeCompare(b.id));this.data.ranking.forEach((f,i)=>f.seed=i+1);const qualifiers=this.data.size/2;this.data.deEntrants=this.data.ranking.slice(0,qualifiers);if(!this.data.deEntrants.some(f=>f.isPlayer)){this.data.phase='eliminated';this.save();return this.showEnd(false,'FAILED TO QUALIFY');}this.data.phase='seeding';this.save();this.showSeeding();},
  startDE(){this.data.phase='de';this.prepareRound(this.data.deEntrants);},
  prepareRound(entrants){const label=this.roundName(entrants.length),pairs=[];for(let i=0;i<entrants.length/2;i++)pairs.push({a:entrants[i],b:entrants[entrants.length-1-i],winner:null,score:null});this.data.currentRound={label,pairs};this.data.deRounds.push(this.data.currentRound);for(const m of pairs)if(!m.a.isPlayer&&!m.b.isPlayer){const [as,bs]=this.simulate(m.a,m.b,15);m.score=`${as} — ${bs}`;m.winner=as>bs?m.a:m.b;}this.save();this.showBracket();},
  startDEPlayer(){const m=this.data.currentRound.pairs.find(x=>x.a.isPlayer||x.b.isPlayer);const opp=m.a.isPlayer?m.b:m.a;configureBout({mode:'tournament',target:15,stage:this.data.currentRound.label,meta:`#${this.player().seed} vs #${opp.seed}`,playerName:this.data.playerName,opponent:opp,difficulty:this.level(opp.skill),tournamentKind:'de',deMatch:m});},
  resolveDERound(won,record){const m=bout.deMatch;m.score=`${record.playerScore} — ${record.opponentScore}`;m.winner=won?this.player():bout.opponent;if(!won){this.data.phase='eliminated';this.save();return this.showEnd(false,`ELIMINATED · ${this.data.currentRound.label}`);}const winners=this.data.currentRound.pairs.map(x=>x.winner);if(winners.length===1){this.data.phase='complete';this.save();this.showEnd(true,'TOURNAMENT CHAMPION');return;}this.prepareRound(winners);},
  showPools(){hideScreens();$('#tournamentScreen').classList.remove('hidden');const pPool=this.data.pools.find(p=>p.fencers.some(f=>f.isPlayer)),next=this.nextPoolBout();$('#tournamentContent').innerHTML=`<div class="tournament-head"><div class="eyebrow">TOURNAMENT · POOL ROUND</div><h2>POOL ${pPool.name}</h2><p>${this.data.size} fencers · Top ${this.data.size/2} advance</p></div><div class="pool-grid"><div class="pool-card"><h3>STANDINGS</h3>${this.table(pPool.fencers)}</div><div class="pool-card"><h3>YOUR SCHEDULE</h3><div class="schedule">${this.data.playerSchedule.map((x,i)=>{const o=this.find(x.opponentId);return `<div class="schedule-item ${x===next?'next':''}"><span>${this.data.playerName} vs ${o.name}</span><b class="${x.won?'win':x.status==='DONE'?'loss':''}">${x.status==='DONE'?`${x.score} · ${x.won?'WIN':'LOSS'}`:x===next?'NEXT':'UPCOMING'}</b></div>`}).join('')}</div></div></div><div class="screen-actions"><button id="nextPool" class="primary">${next?'FENCE NEXT BOUT':'VIEW POOL RESULTS'}</button><button class="exit-menu">SAVE & EXIT</button></div>`;$('#nextPool').onclick=()=>next?this.startNextPool():this.finishPools();wireExit();},
  showSeeding(){hideScreens();$('#tournamentScreen').classList.remove('hidden');$('#tournamentContent').innerHTML=`<div class="tournament-head"><div class="eyebrow">POOL ROUND COMPLETE</div><h2>FINAL SEEDING</h2><p>Ranked by victories, indicator, then touches scored</p></div><div class="pool-card">${this.table(this.data.ranking,true)}</div><div class="screen-actions"><button id="beginDE" class="primary">ENTER DIRECT ELIMINATION</button><button class="exit-menu">SAVE & EXIT</button></div>`;$('#beginDE').onclick=()=>this.startDE();wireExit();},
  showBracket(){hideScreens();$('#tournamentScreen').classList.remove('hidden');const r=this.data.currentRound;$('#tournamentContent').innerHTML=`<div class="tournament-head"><div class="eyebrow">DIRECT ELIMINATION · FIRST TO 15</div><h2>${r.label}</h2><p>One 1-minute break when either fencer first reaches 8</p></div><div class="bracket-card"><h3>CURRENT BRACKET</h3>${r.pairs.map(m=>`<div class="bracket-match"><span>#${m.a.seed} ${m.a.name} vs #${m.b.seed} ${m.b.name}</span><b>${m.score||((m.a.isPlayer||m.b.isPlayer)?'YOUR BOUT':'SIMULATING')}</b></div>`).join('')}</div><div class="screen-actions"><button id="fenceDE" class="primary">FENCE ${r.label}</button><button class="exit-menu">SAVE & EXIT</button></div>`;$('#fenceDE').onclick=()=>this.startDEPlayer();wireExit();},
  showEnd(champion,title){hideScreens();$('#tournamentScreen').classList.remove('hidden');const p=this.player(),s=this.data.stats;$('#tournamentContent').innerHTML=`<div class="result-hero"><div class="trophy">${champion?'🏆':'⚔'}</div><div class="eyebrow">TOURNAMENT COMPLETE</div><h2>${title}</h2><p>${this.data.playerName} · Seed #${p.seed||'—'}</p></div><div class="stat-cards"><div class="stat-card"><b>${s.poolWins}-${s.poolLosses}</b><span>POOL RECORD</span></div><div class="stat-card"><b>${s.deWins}-${s.deLosses}</b><span>DE RECORD</span></div><div class="stat-card"><b>${s.touchesScored-s.touchesReceived>=0?'+':''}${s.touchesScored-s.touchesReceived}</b><span>INDICATOR</span></div><div class="stat-card"><b>${s.successfulTouches}</b><span>TOUCHES</span></div></div><div class="history-card"><h3>MATCH HISTORY</h3><table class="data-table">${this.data.history.map(h=>`<tr><td>${h.stage} · ${h.opponent}</td><td class="${h.won?'win':'loss'}">${h.won?'WIN':'LOSS'}</td><td>${h.playerScore} — ${h.opponentScore}</td></tr>`).join('')}</table></div><div class="screen-actions"><button id="newTournament" class="primary">NEW TOURNAMENT</button><button class="exit-menu">RETURN TO MENU</button></div>`;$('#newTournament').onclick=()=>{$('#tournamentScreen').classList.add('hidden');$('#tournamentSetup').classList.remove('hidden');};wireExit();},
  table(list,seeded=false){const sorted=seeded?list:[...list].sort((a,b)=>b.wins-a.wins||(b.ts-b.tr)-(a.ts-a.tr)||b.ts-a.ts);return `<table class="data-table"><tr><th>FENCER</th><th>V</th><th>L</th><th>TS</th><th>TR</th><th>IND</th></tr>${sorted.map(f=>`<tr class="${f.isPlayer?'player-row':''}"><td>${seeded?`#${f.seed} `:''}${f.name}<small> · ${f.style}</small></td><td>${f.wins}</td><td>${f.losses}</td><td>${f.ts}</td><td>${f.tr}</td><td>${f.ts-f.tr>=0?'+':''}${f.ts-f.tr}</td></tr>`).join('')}</table>`;},
  roundName(n){return n===2?'FINAL':n===4?'SEMIFINAL':n===8?'QUARTERFINAL':`ROUND OF ${n}`;},find(id){return this.data.fencers.find(f=>f.id===id);},player(){return this.data.fencers.find(f=>f.isPlayer);},level(skill){return skill>87?'expert':skill>71?'hard':skill>50?'normal':'easy';},stat(k){if(this.data&&bout.mode==='tournament')this.data.stats[k]=(this.data.stats[k]||0)+1;},trackTouch(reason){if(this.data&&bout.mode==='tournament'){this.data.stats.successfulTouches++;if(reason==='RIPOSTE')flashToast('CLEAN RIPOSTE');}},save(){if(this.data)localStorage.setItem(SAVE_KEY,JSON.stringify(this.data));refreshContinue();}}

function saveTournament(){if(Tournament.data)Tournament.save();}
function loadTournament(){try{Tournament.data=JSON.parse(localStorage.getItem(SAVE_KEY));if(!Tournament.data)return;if(Tournament.data.phase==='pools')Tournament.showPools();else if(Tournament.data.phase==='seeding')Tournament.showSeeding();else if(Tournament.data.phase==='de')Tournament.showBracket();else Tournament.showEnd(Tournament.data.phase==='complete',Tournament.data.phase==='complete'?'TOURNAMENT CHAMPION':'TOURNAMENT ELIMINATED');}catch{localStorage.removeItem(SAVE_KEY);}}
function refreshContinue(){const has=!!localStorage.getItem(SAVE_KEY);$('#continueTournament').classList.toggle('hidden',!has);$('#deleteTournament').classList.toggle('hidden',!has);}

// ---- Rendering ---------------------------------------------------------------
function drawArena(){const g=ctx.createLinearGradient(0,0,0,620);g.addColorStop(0,'#102832');g.addColorStop(.7,'#07151c');g.addColorStop(1,'#03090d');ctx.fillStyle=g;ctx.fillRect(0,0,1200,620);ctx.strokeStyle='#173743';for(let x=0;x<1200;x+=80){ctx.beginPath();ctx.moveTo(600+(x-600)*.42,220);ctx.lineTo(x,560);ctx.stroke();}ctx.fillStyle='#b5d1d633';ctx.beginPath();ctx.moveTo(135,390);ctx.lineTo(1065,390);ctx.lineTo(1160,505);ctx.lineTo(40,505);ctx.closePath();ctx.fill();ctx.strokeStyle='#6d8f9988';ctx.stroke();ctx.setLineDash([10,10]);ctx.beginPath();ctx.moveTo(600,390);ctx.lineTo(600,505);ctx.stroke();ctx.setLineDash([]);}
function drawFencer(f){const c=f===player?'#6ee7ff':'#ff6372',dir=f.facing,duck=f.state===STATE.DUCK?25:0,lunge=f.state===STATE.LUNGE?18:0,x=f.x+dir*lunge,y=duck;ctx.save();ctx.strokeStyle=c;ctx.lineCap='round';ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(x,305+y);ctx.lineTo(x-dir*7,397+y);ctx.stroke();ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(x-5*dir,390+y);ctx.lineTo(x-28*dir,456);ctx.moveTo(x-3*dir,391+y);ctx.lineTo(x+35*dir,456);ctx.stroke();ctx.fillStyle='#d9e4e5';ctx.beginPath();ctx.ellipse(x,276+y,22,27,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=c;ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#17262c';ctx.fillRect(x-dir*18,268+y,dir*18,14);ctx.strokeStyle=c;ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(x,320+y);ctx.lineTo(x+dir*22,304+y);ctx.stroke();const b=blade(f);ctx.strokeStyle='#f5fdff';ctx.lineWidth=3;ctx.shadowBlur=12;ctx.shadowColor=c;ctx.beginPath();ctx.moveTo(b.x1,b.y1+y);ctx.lineTo(b.x2,b.y2+y);ctx.stroke();ctx.restore();}
function refPose(){const s=referee.state,t=Math.min(1,referee.stateTime/(REFEREE_MOVE_DURATION/1000)),e=1-Math.pow(1-t,3);let l={x:-42,y:24},r={x:42,y:24};if(s===REF.UNGARD){l={x:-68,y:-38};r={x:68,y:-38};}else if(s===REF.READY){l={x:-50,y:4};r={x:50,y:4};}else if(s===REF.FENCE){l={x:-28,y:44};r={x:28,y:44};}else if(s===REF.STOP||s===REF.PAUSE){l={x:-65,y:-18};r={x:65,y:-18};}else if(s===REF.PLAYER_POINT||s===REF.MATCH_END&&player.score>computer.score){l={x:-58,y:-70};r={x:36,y:28};}else if(s===REF.COMPUTER_POINT||s===REF.MATCH_END&&computer.score>player.score){l={x:-36,y:28};r={x:58,y:-70};}return{l:{x:l.x*e-35*(1-e),y:l.y*e+24*(1-e)},r:{x:r.x*e+35*(1-e),y:r.y*e+24*(1-e)}};}
function drawReferee(){const x=600,y=205,p=refPose(),focus=[REF.STOP,REF.PLAYER_POINT,REF.COMPUTER_POINT,REF.MATCH_END].includes(referee.state);ctx.save();if(focus){const g=ctx.createRadialGradient(x,y,10,x,y,125);g.addColorStop(0,'#fff3');g.addColorStop(1,'#fff0');ctx.fillStyle=g;ctx.fillRect(x-130,y-110,260,240);}ctx.lineCap='round';ctx.strokeStyle='#11191d';ctx.lineWidth=13;ctx.beginPath();ctx.moveTo(x,y+30);ctx.lineTo(x,y+115);ctx.moveTo(x,y+108);ctx.lineTo(x-25,y+160);ctx.moveTo(x,y+108);ctx.lineTo(x+25,y+160);ctx.stroke();ctx.beginPath();ctx.moveTo(x-3,y+43);ctx.lineTo(x+p.l.x,y+43+p.l.y);ctx.moveTo(x+3,y+43);ctx.lineTo(x+p.r.x,y+43+p.r.y);ctx.strokeStyle='#81949b';ctx.lineWidth=14;ctx.stroke();ctx.strokeStyle='#11191d';ctx.lineWidth=9;ctx.stroke();ctx.fillStyle='#d2a88e';for(const q of[p.l,p.r]){ctx.beginPath();ctx.arc(x+q.x,y+43+q.y,7,0,Math.PI*2);ctx.fill();}ctx.beginPath();ctx.arc(x,y+4,19,0,Math.PI*2);ctx.fill();ctx.fillStyle='#0b1115';ctx.fillRect(x-20,y-1,40,10);ctx.fillStyle='#dce9eb';ctx.font='700 9px Segoe UI';ctx.textAlign='center';ctx.fillText('REFEREE',x,y+82);ctx.restore();}
function spawnSparks(x,y,color,n){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*330,vy:(Math.random()-.8)*260,life:.3+Math.random()*.35,color});}
function updateParticles(dt){for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=340*dt;p.life-=dt;}particles=particles.filter(p=>p.life>0);}
function render(){ctx.save();if(shake>0){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.88;}drawArena();drawReferee();drawFencer(player);drawFencer(computer);for(const p of particles){ctx.globalAlpha=Math.min(1,p.life*4);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,3,3);}ctx.globalAlpha=1;ctx.restore();}
function updateUI(){ui.stamina.style.width=`${player.stamina}%`;ui.combo.textContent=player.riposteWindow>0?'RIPOSTE WINDOW!':player.state.toUpperCase();const d=computer.x-player.x;ui.distance.textContent=d>360?'DISTANCE: OUT OF RANGE':d>270?'DISTANCE: LUNGE MEASURE':d>155?'DISTANCE: ATTACK RANGE':'DISTANCE: VERY CLOSE';}

// ---- Overlays, audio and menu wiring -----------------------------------------
function showAnnouncement(top,main,sub){ui.annTop.textContent=top;ui.annMain.textContent=main;ui.annSub.textContent=sub;ui.ann.classList.remove('hidden');}
function flashToast(text){ui.toast.textContent=text;ui.toast.classList.add('show');toastTimer=.9;}
function tone(freq,duration){if(!soundOn)return;try{const ac=tone.ac||(tone.ac=new(AudioContext||webkitAudioContext)()),o=ac.createOscillator(),g=ac.createGain();o.frequency.value=freq;o.type='triangle';g.gain.setValueAtTime(.07,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+duration);o.connect(g).connect(ac.destination);o.start();o.stop(ac.currentTime+duration);}catch{}}
function toggleMusic(){musicOn=!musicOn;$('#musicButton').textContent=`MUSIC ${musicOn?'ON':'OFF'}`;$('#settingsMusic').textContent=musicOn?'ON':'OFF';if(musicTimer)clearInterval(musicTimer);if(musicOn)musicTimer=setInterval(()=>tone(90+Math.random()*20,1.4),1800);}
function hideScreens(){document.querySelectorAll('.screen-modal').forEach(x=>x.classList.add('hidden'));}
function exitMenu(){hideScreens();ui.pause.classList.add('hidden');ui.match.classList.add('hidden');ui.breakOverlay.classList.add('hidden');ui.menu.classList.remove('hidden');gameState=GAME.MENU;setRef(REF.IDLE);refreshContinue();}
function wireExit(){document.querySelectorAll('.exit-menu').forEach(b=>b.onclick=exitMenu);}
function togglePause(){if([GAME.MENU,GAME.OVER,GAME.BREAK].includes(gameState))return;if(gameState===GAME.PAUSED){gameState=previousState;ui.pause.classList.add('hidden');lastTime=performance.now();}else{previousState=gameState;gameState=GAME.PAUSED;setRef(REF.PAUSE);ui.pause.classList.remove('hidden');}}
function requestRestart(){if([GAME.MENU,GAME.OVER,GAME.BREAK].includes(gameState))return;restartPaused=gameState!==GAME.PAUSED;if(restartPaused)togglePause();$('#restartModal').classList.remove('hidden');}
function cancelRestart(){ $('#restartModal').classList.add('hidden');if(restartPaused&&gameState===GAME.PAUSED)togglePause();restartPaused=false;}
function openHelp(){instructionsPaused=![GAME.MENU,GAME.OVER,GAME.PAUSED,GAME.BREAK].includes(gameState);if(instructionsPaused)togglePause();$('#howToPlayModal').classList.remove('hidden');}
function closeHelp(){if($('#howToPlayModal').classList.contains('hidden'))return;$('#howToPlayModal').classList.add('hidden');if(instructionsPaused&&gameState===GAME.PAUSED)togglePause();instructionsPaused=false;}
function closeTopModal(){if(!$('#howToPlayModal').classList.contains('hidden'))closeHelp();else if(!$('#restartModal').classList.contains('hidden'))cancelRestart();}
function choose(container,attribute,callback){container.querySelectorAll(`button[data-${attribute}]`).forEach(b=>b.onclick=()=>{container.querySelectorAll(`button[data-${attribute}]`).forEach(x=>x.classList.toggle('selected',x===b));callback(b.dataset[attribute]);});}

let quickTarget=5,tournamentSize=16,practiceStyle='BALANCED';
$('#tournamentButton').onclick=()=>{$('#menu').classList.add('hidden');$('#tournamentSetup').classList.remove('hidden');};$('#quickBoutButton').onclick=()=>{$('#menu').classList.add('hidden');$('#quickSetup').classList.remove('hidden');};$('#practiceButton').onclick=()=>{$('#menu').classList.add('hidden');$('#practiceSetup').classList.remove('hidden');};
$('#startQuick').onclick=()=>configureBout({mode:'quick',target:quickTarget,stage:'QUICK BOUT',opponent:{name:'COMPUTER',style:'BALANCED'},difficulty});$('#startPractice').onclick=()=>configureBout({mode:'practice',target:999,stage:'PRACTICE',opponent:{name:'TRAINING AI',style:practiceStyle},difficulty});$('#startTournament').onclick=()=>Tournament.new(tournamentSize,$('#playerNameInput').value.trim()||'RAY');
choose($('#quickTargets'),'target',v=>quickTarget=+v);choose($('#sizeChoices'),'size',v=>tournamentSize=+v);choose($('#practiceStyles'),'style',v=>practiceStyle=v);document.querySelectorAll('.difficulty-choices').forEach(c=>choose(c,'difficulty',v=>difficulty=v));
document.querySelectorAll('.how-to-play-button').forEach(b=>b.onclick=openHelp);$('#closeHowToPlay').onclick=closeHelp;$('#closeHowToPlayX').onclick=closeHelp;$('#howToPlayModal').onclick=e=>{if(e.target.id==='howToPlayModal')closeHelp();};
document.querySelectorAll('.restart-request').forEach(b=>b.onclick=requestRestart);$('#confirmRestart').onclick=()=>{$('#restartModal').classList.add('hidden');restartPaused=false;ui.pause.classList.add('hidden');resetBout();};$('#cancelRestart').onclick=cancelRestart;$('#resumeButton').onclick=togglePause;wireExit();
$('#settingsButton').onclick=()=>{$('#menu').classList.add('hidden');$('#settingsModal').classList.remove('hidden');};document.querySelectorAll('.close-settings').forEach(b=>b.onclick=()=>{$('#settingsModal').classList.add('hidden');$('#menu').classList.remove('hidden');});$('#soundButton').onclick=()=>{soundOn=!soundOn;$('#soundButton').textContent=`SOUND ${soundOn?'ON':'OFF'}`;$('#settingsSound').textContent=soundOn?'ON':'OFF';};$('#settingsSound').onclick=()=>$('#soundButton').click();$('#musicButton').onclick=toggleMusic;$('#settingsMusic').onclick=toggleMusic;
$('#continueTournament').onclick=loadTournament;$('#deleteTournament').onclick=()=>{localStorage.removeItem(SAVE_KEY);Tournament.data=null;refreshContinue();};$('#skipBreakButton').onclick=()=>endBreak(true);

function loop(now){const raw=Math.min(.035,(now-lastTime)/1000||0);lastTime=now;const dt=raw*slowMotion;if(![GAME.PAUSED,GAME.MENU,GAME.BREAK,GAME.OVER].includes(gameState)){referee.stateTime+=raw;if([GAME.UNGARD,GAME.READY].includes(gameState))updateSequence(raw);if(gameState===GAME.FENCE){handlePlayer(dt);updateAI(dt);updateFencer(player,dt);updateFencer(computer,dt);resolveCombat(player,computer);resolveCombat(computer,player);}if(gameState===GAME.HALT)updateHalt(raw);updateParticles(raw);if(toastTimer>0&&(toastTimer-=raw)<=0)ui.toast.classList.remove('show');updateUI();}render();pressed.clear();requestAnimationFrame(loop);}
document.querySelectorAll('.copyright-year').forEach(element=>element.textContent=new Date().getFullYear());
refreshContinue();requestAnimationFrame(loop);
