'use strict';

// ---- Tunable rules and timing ------------------------------------------------
const TARGET_SCORE=5, COMBO_WINDOW=520, REFEREE_SIGNAL_DURATION=3000, REFEREE_MOVE_DURATION=400, REFEREE_HALT_DURATION=350, STRIP={left:80,right:1120,y:438};
const GAME={MENU:'menu',UNGARD:'ungard',READY:'ready',FENCE:'fence',HALT:'halt',POINT:'point',OVER:'over',PAUSED:'paused'};
const STATE={GUARD:'guard',ADVANCE:'advance',RETREAT:'retreat',ATTACK:'attack',LUNGE:'lunge',PARRY:'parry',RIPOSTE:'riposte',DUCK:'duck',HIT:'hit',RECOVER:'recover'};
const REFEREE_STATES={IDLE:'idle',UNGARD:'ungard',READY:'ready',FENCE:'fence',STOP:'stop',PLAYER_POINT:'player_point',COMPUTER_POINT:'computer_point',NO_TOUCH:'no_touch',PAUSE:'pause',MATCH_END:'match_end',CLASH:'clash'};
const ACTION_RESULTS={MISS:'MISS',OUT_OF_RANGE:'OUT_OF_RANGE',BLADE_CONTACT:'BLADE_CONTACT',PARRIED:'PARRIED',TOUCH:'TOUCH'};
const SIDES={player:'left',computer:'right'};
const DIFFICULTIES={easy:{reaction:.48,skill:.28,aggression:.32},normal:{reaction:.30,skill:.55,aggression:.52},hard:{reaction:.17,skill:.78,aggression:.66}};
const canvas=document.querySelector('#gameCanvas'),ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s); const ui={menu:$('#menu'),announcement:$('#announcement'),annTop:$('#announcementTop'),annMain:$('#announcementMain'),annSub:$('#announcementSub'),toast:$('#toast'),ps:$('#playerScore'),cs:$('#computerScore'),round:$('#roundLabel'),distance:$('#distanceLabel'),stamina:$('#staminaFill'),combo:$('#comboLabel'),pause:$('#pauseOverlay'),match:$('#matchOverlay'),result:$('#matchResult'),summary:$('#matchSummary'),refPanel:$('#refereePanel'),refDecision:$('#refereeDecision'),refReason:$('#refereeReason'),refStatus:$('#refereeStatus')};

let gameState=GAME.MENU,previousState=GAME.MENU,difficulty='normal',practice=false,point=1,lastTime=0,sequenceTimer=0,pointTimer=0,slowMotion=1,shake=0,soundOn=true,particles=[],inputHistory=[],toastTimer=0,currentDecision=null;
const referee={state:REFEREE_STATES.IDLE,stateTime:0,signalSide:null,signalStartTime:null};
let instructionsPausedGame=false;
const keys=new Set(),pressed=new Set();

function makeFencer(side){return {side,x:side==='player'?330:870,vx:0,facing:side==='player'?1:-1,state:STATE.GUARD,stateTime:0,actionTime:0,stamina:100,score:0,attackId:0,hitResolved:false,parrySuccess:false,riposteWindow:0,priorityTime:Infinity,aiTimer:0,aiIntent:'idle',pattern:[]};}
let player=makeFencer('player'),computer=makeFencer('computer');

// ---- Input -------------------------------------------------------------------
const movement={left:['KeyA','ArrowLeft'],right:['KeyD','ArrowRight'],burst:['KeyW','ArrowUp'],duck:['KeyS','ArrowDown']};
const down=name=>movement[name].some(k=>keys.has(k));
addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space'].includes(e.code))e.preventDefault();if(!keys.has(e.code))pressed.add(e.code);keys.add(e.code);if(e.code==='KeyP'&&!e.repeat)togglePause();if(e.code==='KeyR'&&!e.repeat)restart();});
addEventListener('keyup',e=>keys.delete(e.code)); addEventListener('blur',()=>keys.clear());
function recordInput(code){inputHistory.push({code,t:performance.now()});inputHistory=inputHistory.filter(i=>performance.now()-i.t<COMBO_WINDOW*2);}
function hasCombo(seq){let at=0,start=0;for(const i of inputHistory){if(i.code===seq[at]){if(!at)start=i.t;if(++at===seq.length)return i.t-start<=COMBO_WINDOW;}}return false;}

// ---- Match flow ---------------------------------------------------------------
function start(mode){practice=mode==='practice';ui.menu.classList.add('hidden');resetScores();beginPoint();}
function resetScores(){player=makeFencer('player');computer=makeFencer('computer');point=1;particles=[];updateScore();}
function resetPositions(){Object.assign(player,makeFencer('player'),{score:player.score});Object.assign(computer,makeFencer('computer'),{score:computer.score});}
function setRefereeState(state){referee.state=state;referee.stateTime=0;ui.refStatus.textContent=`REFEREE · ${state.replace('_',' ').toUpperCase()}`;}
function beginPoint(){resetPositions();currentDecision=null;ui.refPanel.classList.add('hidden');gameState=GAME.UNGARD;sequenceTimer=0;setRefereeState(REFEREE_STATES.UNGARD);showAnnouncement(point>1&&((player.score===TARGET_SCORE-1)||(computer.score===TARGET_SCORE-1))?'MATCH POINT':`POINT ${point}`,'UNGARD','REFEREE CALL');tone(220,.08);}
function updateSequence(dt){sequenceTimer+=dt;if(gameState===GAME.UNGARD&&sequenceTimer>1){gameState=GAME.READY;sequenceTimer=0;setRefereeState(REFEREE_STATES.READY);showAnnouncement(`POINT ${point}`,'READY','REFEREE CALL');tone(330,.08);}else if(gameState===GAME.READY&&sequenceTimer>.9){gameState=GAME.FENCE;sequenceTimer=0;setRefereeState(REFEREE_STATES.FENCE);showAnnouncement('','FENCE!','REFEREE CALL');tone(660,.13);setTimeout(()=>{if(gameState===GAME.FENCE){ui.announcement.classList.add('hidden');setRefereeState(REFEREE_STATES.IDLE);}},520);}}
// Only a validated TOUCH enters this single authoritative referee/scoring path.
function scoreTouch(winner,reason,detail){return resolveRefereeDecision({type:ACTION_RESULTS.TOUCH,scorer:winner.side,reason,detail:detail||reason});}
function resolveRefereeDecision(result){if(gameState!==GAME.FENCE||result.type!==ACTION_RESULTS.TOUCH)return result;currentDecision={...result,signalStarted:false,scoreApplied:false};gameState=GAME.HALT;pointTimer=0;slowMotion=.28;shake=10;referee.signalSide=SIDES[result.scorer];referee.signalStartTime=null;setRefereeState(REFEREE_STATES.STOP);showAnnouncement('REFEREE','HALT!','ANALYZING PHRASE');ui.refPanel.classList.add('hidden');tone(180,.12);return result;}
function startRefereeSignal(){if(!currentDecision||currentDecision.signalStarted)return;currentDecision.signalStarted=true;referee.signalStartTime=performance.now();ui.announcement.classList.add('hidden');ui.refPanel.classList.remove('hidden');ui.refDecision.textContent=`TOUCH — ${currentDecision.scorer.toUpperCase()}`;ui.refReason.textContent=currentDecision.reason;setRefereeState(currentDecision.scorer==='player'?REFEREE_STATES.PLAYER_POINT:REFEREE_STATES.COMPUTER_POINT);tone(currentDecision.scorer==='player'?880:150,.18);}
function applyScoreAfterSignal(){if(!currentDecision||currentDecision.scoreApplied)return;currentDecision.scoreApplied=true;const winner=currentDecision.scorer==='player'?player:computer;winner.score++;spawnSparks(winner===player?computer.x:player.x,320,winner===player?'#57e3ff':'#ff5a69',28);flashToast(`${currentDecision.scorer.toUpperCase()} +1 · ${currentDecision.detail}`);tone(winner===player?880:150,.25);updateScore();}
function updatePointPause(dt){pointTimer+=dt;slowMotion=Math.min(1,slowMotion+dt*1.8);if(pointTimer>=REFEREE_HALT_DURATION/1000)startRefereeSignal();if(!currentDecision?.signalStarted)return;const signalElapsed=performance.now()-referee.signalStartTime;if(signalElapsed>=REFEREE_MOVE_DURATION+REFEREE_SIGNAL_DURATION)applyScoreAfterSignal();if(currentDecision.scoreApplied&&signalElapsed>=REFEREE_MOVE_DURATION+REFEREE_SIGNAL_DURATION+550){if(!practice&&(player.score>=TARGET_SCORE||computer.score>=TARGET_SCORE)){gameState=GAME.OVER;setRefereeState(REFEREE_STATES.MATCH_END);ui.refPanel.classList.add('hidden');ui.announcement.classList.add('hidden');ui.match.classList.remove('hidden');ui.result.textContent=player.score>computer.score?'PLAYER WINS':'COMPUTER WINS';ui.summary.textContent=`HALT · FINAL SCORE ${player.score} — ${computer.score}`;}else{point++;beginPoint();}}}
function restart(){ui.match.classList.add('hidden');ui.pause.classList.add('hidden');if(gameState===GAME.MENU)return;resetScores();beginPoint();}
function togglePause(){if([GAME.MENU,GAME.OVER].includes(gameState))return;if(gameState===GAME.PAUSED){gameState=previousState;setRefereeState(previousState===GAME.FENCE?REFEREE_STATES.IDLE:referee.state);ui.pause.classList.add('hidden');lastTime=performance.now();}else{previousState=gameState;setRefereeState(REFEREE_STATES.PAUSE);gameState=GAME.PAUSED;ui.pause.classList.remove('hidden');}}
function openHowToPlay(){instructionsPausedGame=![GAME.MENU,GAME.OVER,GAME.PAUSED].includes(gameState);if(instructionsPausedGame)togglePause();$('#howToPlayModal').classList.remove('hidden');$('#closeHowToPlayX').focus();}
function closeHowToPlay(){const modal=$('#howToPlayModal');if(modal.classList.contains('hidden'))return;modal.classList.add('hidden');if(instructionsPausedGame&&gameState===GAME.PAUSED)togglePause();instructionsPausedGame=false;}

// ---- Fencer actions and combat ------------------------------------------------
function canAct(f){return [STATE.GUARD,STATE.ADVANCE,STATE.RETREAT,STATE.DUCK].includes(f.state);}
function beginAction(f,state){if(!canAct(f))return false;const cost=state===STATE.LUNGE?24:state===STATE.ATTACK?11:state===STATE.PARRY?8:13;if(f.stamina<cost)return false;f.stamina-=cost;f.state=state;f.stateTime=0;f.actionTime=0;f.hitResolved=false;f.attackId++;if([STATE.ATTACK,STATE.LUNGE,STATE.RIPOSTE].includes(state))f.priorityTime=performance.now();return true;}
function attack(f,type=STATE.ATTACK){if(beginAction(f,type)){tone(300,.04);if(f===player)flashToast(type===STATE.LUNGE?'LUNGE!':'ATTACK!');}}
function parry(f){if(beginAction(f,STATE.PARRY)){tone(520,.03);if(f===player)flashToast('PARRY!');}}
function riposte(f){if(f.riposteWindow>0&&canAct(f)){beginAction(f,STATE.RIPOSTE);f.priorityTime=performance.now()-1000;if(f===player)flashToast('RIPOSTE!');}else if(f===player)flashToast('NO RIPOSTE WINDOW');}
function feint(f){if([STATE.ATTACK,STATE.LUNGE].includes(f.state)&&f.stateTime<.18){f.state=STATE.RECOVER;f.stateTime=0;f.priorityTime=Infinity;if(f===player)flashToast('FEINT');return true;}return false;}
function actionPhase(f){const t=f.stateTime;if(f.state===STATE.ATTACK)return t<.13?'startup':t<.25?'active':t<.48?'recovery':'done';if(f.state===STATE.LUNGE)return t<.16?'startup':t<.34?'active':t<.65?'recovery':'done';if(f.state===STATE.RIPOSTE)return t<.07?'startup':t<.22?'active':t<.42?'recovery':'done';if(f.state===STATE.PARRY)return t<.08?'startup':t<.27?'active':t<.45?'recovery':'done';return ''}
function bladeGeometry(f){const phase=actionPhase(f),attacking=['active'].includes(phase)&&[STATE.ATTACK,STATE.LUNGE,STATE.RIPOSTE].includes(f.state);const parrying=f.state===STATE.PARRY&&phase==='active';const crouch=f.state===STATE.DUCK;const handX=f.x+f.facing*20,handY=crouch?337:300;const extension=attacking?(f.state===STATE.LUNGE?150:132):parrying?84:92;const angle=parrying?-f.facing*1.05:attacking?-.04*f.facing:-.28*f.facing;return {x1:handX,y1:handY,x2:handX+Math.cos(angle)*extension*f.facing,y2:handY+Math.sin(angle)*extension};}
function targets(f){const duck=f.state===STATE.DUCK?25:0;return [{x:f.x-18,y:245+duck,w:36,h:55,name:'head'},{x:f.x-30,y:300+duck,w:60,h:100,name:'torso'},{x:f.x-42,y:305+duck,w:84,h:24,name:'arms'}];}
function lineRect(line,r){const steps=14;for(let i=0;i<=steps;i++){const t=i/steps,x=line.x1+(line.x2-line.x1)*t,y=line.y1+(line.y2-line.y1)*t;if(x>=r.x&&x<=r.x+r.w&&y>=r.y&&y<=r.y+r.h)return true;}return false;}
function bladesCross(a,b){const A=bladeGeometry(a),B=bladeGeometry(b);return Math.abs(A.x2-B.x2)<58&&Math.abs(A.y2-B.y2)<70;}
function resolveCombat(attacker,defender){if(attacker.hitResolved||actionPhase(attacker)!=='active')return null;attacker.hitResolved=true;if(defender.state===STATE.PARRY&&actionPhase(defender)==='active'&&bladesCross(attacker,defender)){attacker.state=STATE.RECOVER;attacker.stateTime=0;defender.parrySuccess=true;defender.riposteWindow=.62;defender.priorityTime=performance.now()-1200;spawnSparks((attacker.x+defender.x)/2,290,'#fff4bd',14);flashToast(defender===player?'PARRIED — RIPOSTE NOW!':'COMPUTER PARRY');tone(920,.1);return {type:ACTION_RESULTS.PARRIED};}
  const blade=bladeGeometry(attacker),hit=targets(defender).some(r=>lineRect(blade,r));if(!hit){const outOfRange=Math.abs(attacker.x-defender.x)>260;if(attacker===player)flashToast(outOfRange?'OUT OF RANGE':'MISS');return {type:outOfRange?ACTION_RESULTS.OUT_OF_RANGE:ACTION_RESULTS.MISS};}
  const otherActive=['ATTACK','LUNGE','RIPOSTE'].includes(defender.state?.toUpperCase())&&actionPhase(defender)==='active';if(otherActive&&!defender.hitResolved){const winner=attacker.priorityTime<=defender.priorityTime?attacker:defender;attacker.hitResolved=defender.hitResolved=true;scoreTouch(winner,winner.state===STATE.RIPOSTE?'RIPOSTE':'PRIORITY',`Double attack — ${winner===player?'your':'computer'} priority`);}else scoreTouch(attacker,attacker.state===STATE.RIPOSTE?'RIPOSTE':attacker.state===STATE.LUNGE?'LUNGE ATTACK':'ATTACK',attacker.priorityTime<performance.now()-650?'Attack maintained priority':'Clean target hit');}

function updateFencer(f,dt){f.stateTime+=dt;f.riposteWindow=Math.max(0,f.riposteWindow-dt);f.stamina=Math.min(100,f.stamina+dt*(f.state===STATE.GUARD?20:9));if(f.state===STATE.LUNGE&&f.stateTime<.32)f.x+=f.facing*390*dt;if(f.state===STATE.RIPOSTE&&f.stateTime<.2)f.x+=f.facing*230*dt;if(['done'].includes(actionPhase(f))||f.state===STATE.RECOVER&&f.stateTime>.25){f.state=STATE.GUARD;f.stateTime=0;f.parrySuccess=false;f.priorityTime=Infinity;}f.x=Math.max(STRIP.left+45,Math.min(STRIP.right-45,f.x));}
function handlePlayer(dt){if(pressed.has('KeyJ')){recordInput('J');attack(player,hasCombo(['D','SPACE','J'])?STATE.LUNGE:STATE.ATTACK);}if(pressed.has('Space')){recordInput('SPACE');attack(player,STATE.LUNGE);}if(pressed.has('KeyK')){recordInput('K');if(!feint(player))parry(player);}if(pressed.has('KeyL')){recordInput('L');riposte(player);}if(pressed.has('KeyD')||pressed.has('ArrowRight'))recordInput('D');
  if(canAct(player)){let dir=0;if(down('left'))dir--;if(down('right'))dir++;let speed=190;if(down('burst')&&player.stamina>3){speed=285;player.stamina-=12*dt;}if(down('duck'))player.state=STATE.DUCK;else if(dir){player.state=dir>0?STATE.ADVANCE:STATE.RETREAT;player.x+=dir*speed*dt;}else if(player.state!==STATE.DUCK)player.state=STATE.GUARD;}}

// ---- Readable state-machine AI ------------------------------------------------
function updateAI(dt){const cfg=DIFFICULTIES[difficulty],dist=computer.x-player.x;computer.aiTimer-=dt;if(player.state===STATE.ATTACK||player.state===STATE.LUNGE){if(computer.aiTimer<=0){computer.aiTimer=cfg.reaction;if(Math.random()<cfg.skill*(dist<300?1:.35))computer.aiIntent=Math.random()<cfg.skill?'parry':'retreat';}}
  if(computer.riposteWindow>0&&canAct(computer)){riposte(computer);computer.aiIntent='recover';return;}if(computer.aiTimer<=0&&canAct(computer)){computer.aiTimer=.18+Math.random()*.35;if(computer.aiIntent==='parry'){parry(computer);computer.aiIntent='recover';return;}if(computer.aiIntent==='retreat'){computer.aiIntent=Math.random()<.55?'retreat':'idle';}else if(dist>350)computer.aiIntent='approach';else if(dist<155)computer.aiIntent=Math.random()<.7?'retreat':'parry';else if(dist<285&&Math.random()<cfg.aggression)computer.aiIntent=Math.random()<.45? 'lunge':'attack';else computer.aiIntent=Math.random()<.45?'approach':'retreat';}
  if(canAct(computer)){if(computer.aiIntent==='attack'){attack(computer);computer.aiIntent='recover';}else if(computer.aiIntent==='lunge'){attack(computer,STATE.LUNGE);computer.aiIntent='recover';}else if(computer.aiIntent==='parry'){parry(computer);computer.aiIntent='recover';}else{const dir=computer.aiIntent==='approach'?-1:computer.aiIntent==='retreat'?1:0;computer.x+=dir*(difficulty==='hard'?175:145)*dt;computer.state=dir<0?STATE.ADVANCE:dir>0?STATE.RETREAT:STATE.GUARD;}}}

// ---- Rendering ----------------------------------------------------------------
function drawArena(){const g=ctx.createLinearGradient(0,0,0,620);g.addColorStop(0,'#102832');g.addColorStop(.7,'#07151c');g.addColorStop(1,'#03090d');ctx.fillStyle=g;ctx.fillRect(0,0,1200,620);ctx.strokeStyle='#173743';ctx.lineWidth=1;for(let x=0;x<1200;x+=80){ctx.beginPath();ctx.moveTo(600+(x-600)*.42,220);ctx.lineTo(x,560);ctx.stroke()}ctx.fillStyle='#b5d1d633';ctx.beginPath();ctx.moveTo(135,390);ctx.lineTo(1065,390);ctx.lineTo(1160,505);ctx.lineTo(40,505);ctx.closePath();ctx.fill();ctx.strokeStyle='#6d8f9988';ctx.stroke();ctx.strokeStyle='#e8ffff66';ctx.setLineDash([10,10]);ctx.beginPath();ctx.moveTo(600,390);ctx.lineTo(600,505);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#ff5a6922';ctx.fillRect(40,485,120,20);ctx.fillStyle='#57e3ff22';ctx.fillRect(1040,485,120,20);}
function drawFencer(f){const c=f===player?'#6ee7ff':'#ff6372',dir=f.facing,duck=f.state===STATE.DUCK?25:0,lunge=f.state===STATE.LUNGE?18:0,x=f.x+dir*lunge,y=duck;ctx.save();if(f.state===STATE.HIT)ctx.globalAlpha=.5;ctx.strokeStyle=c;ctx.fillStyle='#dce9eb';ctx.lineWidth=9;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x,305+y);ctx.lineTo(x-dir*7,397+y);ctx.stroke();ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(x-5*dir,390+y);ctx.lineTo(x-28*dir,456);ctx.moveTo(x-3*dir,391+y);ctx.lineTo(x+35*dir,456);ctx.stroke();ctx.fillStyle='#d9e4e5';ctx.beginPath();ctx.ellipse(x,276+y,22,27,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=c;ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#17262c';ctx.fillRect(x-dir*18,268+y,dir*18,14);ctx.strokeStyle=c;ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(x,320+y);ctx.lineTo(x+dir*22,304+y);ctx.stroke();const b=bladeGeometry(f);ctx.strokeStyle='#f5fdff';ctx.lineWidth=3;ctx.shadowBlur=12;ctx.shadowColor=c;ctx.beginPath();ctx.moveTo(b.x1,b.y1+y);ctx.lineTo(b.x2,b.y2+y);ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle=c;ctx.beginPath();ctx.arc(b.x1,b.y1+y,5,0,Math.PI*2);ctx.fill();ctx.restore();}
function refereePose(){const s=referee.state,t=Math.min(1,referee.stateTime/(REFEREE_MOVE_DURATION/1000)),ease=1-Math.pow(1-t,3);let left={x:-42,y:24},right={x:42,y:24};if(s===REFEREE_STATES.UNGARD){left={x:-68,y:-38};right={x:68,y:-38};}else if(s===REFEREE_STATES.READY){left={x:-50,y:4};right={x:50,y:4};}else if(s===REFEREE_STATES.FENCE){left={x:-28,y:44};right={x:28,y:44};}else if(s===REFEREE_STATES.STOP||s===REFEREE_STATES.PAUSE){left={x:-65,y:-18};right={x:65,y:-18};}else if(s===REFEREE_STATES.PLAYER_POINT||s===REFEREE_STATES.MATCH_END&&player.score>computer.score){left={x:-58,y:-70};right={x:36,y:28};}else if(s===REFEREE_STATES.COMPUTER_POINT||s===REFEREE_STATES.MATCH_END&&computer.score>player.score){left={x:-36,y:28};right={x:58,y:-70};}else if(s===REFEREE_STATES.NO_TOUCH){left={x:-70,y:-42};right={x:70,y:-42};}return {left:{x:left.x*ease+(-35)*(1-ease),y:left.y*ease+24*(1-ease)},right:{x:right.x*ease+35*(1-ease),y:right.y*ease+24*(1-ease)}};}
function drawReferee(){const x=600,y=205,p=refereePose(),focus=[REFEREE_STATES.STOP,REFEREE_STATES.PLAYER_POINT,REFEREE_STATES.COMPUTER_POINT,REFEREE_STATES.NO_TOUCH,REFEREE_STATES.MATCH_END].includes(referee.state);ctx.save();if(focus){const glow=ctx.createRadialGradient(x,y,10,x,y,125);glow.addColorStop(0,'#fff3');glow.addColorStop(1,'#fff0');ctx.fillStyle=glow;ctx.fillRect(x-130,y-110,260,240);}ctx.strokeStyle='#10181d';ctx.fillStyle='#151e23';ctx.lineCap='round';ctx.lineWidth=13;ctx.beginPath();ctx.moveTo(x,y+30);ctx.lineTo(x,y+115);ctx.moveTo(x,y+108);ctx.lineTo(x-25,y+160);ctx.moveTo(x,y+108);ctx.lineTo(x+25,y+160);ctx.stroke();ctx.beginPath();ctx.moveTo(x-3,y+43);ctx.lineTo(x+p.left.x,y+43+p.left.y);ctx.moveTo(x+3,y+43);ctx.lineTo(x+p.right.x,y+43+p.right.y);ctx.strokeStyle='#7e929a';ctx.lineWidth=14;ctx.stroke();ctx.strokeStyle='#10181d';ctx.lineWidth=9;ctx.stroke();ctx.fillStyle='#d2a88e';ctx.beginPath();ctx.arc(x+p.left.x,y+43+p.left.y,7,0,Math.PI*2);ctx.arc(x+p.right.x,y+43+p.right.y,7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d2a88e';ctx.beginPath();ctx.arc(x,y+4,19,0,Math.PI*2);ctx.fill();ctx.fillStyle='#0b1115';ctx.fillRect(x-20,y-1,40,10);ctx.fillStyle='#dce9eb';ctx.font='700 9px Segoe UI';ctx.textAlign='center';ctx.fillText('REFEREE',x,y+82);ctx.restore();}
function spawnSparks(x,y,color,count){for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*330,vy:(Math.random()-.8)*260,life:.3+Math.random()*.35,color});}
function updateParticles(dt){for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=340*dt;p.life-=dt;}particles=particles.filter(p=>p.life>0);}
function renderParticles(){for(const p of particles){ctx.globalAlpha=Math.min(1,p.life*4);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,3,3)}ctx.globalAlpha=1;}
function render(){ctx.save();if(shake>0){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.88;}drawArena();drawReferee();drawFencer(player);drawFencer(computer);renderParticles();ctx.restore();if(window.DEBUG){ctx.fillStyle='white';ctx.fillText(`${gameState} | ${player.state} | ${computer.state} | REF ${referee.state}`,20,25);}}

function updateUI(){ui.stamina.style.width=`${player.stamina}%`;ui.combo.textContent=player.riposteWindow>0?'RIPOSTE WINDOW!':player.state.toUpperCase();const d=computer.x-player.x;ui.distance.textContent=d>360?'DISTANCE: OUT OF RANGE':d>270?'DISTANCE: LUNGE MEASURE':d>155?'DISTANCE: ATTACK RANGE':'DISTANCE: VERY CLOSE';}
function updateScore(){ui.ps.textContent=player.score;ui.cs.textContent=computer.score;ui.round.textContent=practice?`PRACTICE · TOUCHES ${player.score+computer.score}`:`FIRST TO ${TARGET_SCORE}`;}
function showAnnouncement(top,main,sub){ui.annTop.textContent=top;ui.annMain.textContent=main;ui.annSub.textContent=sub;ui.announcement.classList.remove('hidden');}
function flashToast(text){ui.toast.textContent=text;ui.toast.classList.add('show');toastTimer=.8;}
function tone(freq,duration){if(!soundOn)return;try{const ac=tone.ac||(tone.ac=new (AudioContext||webkitAudioContext)()),o=ac.createOscillator(),g=ac.createGain();o.frequency.value=freq;o.type='triangle';g.gain.setValueAtTime(.08,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+duration);o.connect(g).connect(ac.destination);o.start();o.stop(ac.currentTime+duration);}catch{}}

function loop(now){const raw=Math.min(.035,(now-lastTime)/1000||0);lastTime=now;const dt=raw*slowMotion;if(gameState!==GAME.PAUSED){referee.stateTime+=raw;if(gameState===GAME.UNGARD||gameState===GAME.READY)updateSequence(raw);if(gameState===GAME.FENCE){handlePlayer(dt);updateAI(dt);updateFencer(player,dt);updateFencer(computer,dt);resolveCombat(player,computer);resolveCombat(computer,player);}if(gameState===GAME.HALT)updatePointPause(raw);updateParticles(raw);if(toastTimer>0){toastTimer-=raw;if(toastTimer<=0)ui.toast.classList.remove('show');}updateUI();}render();pressed.clear();requestAnimationFrame(loop);}

document.querySelectorAll('[data-difficulty]').forEach(b=>b.onclick=()=>{difficulty=b.dataset.difficulty;document.querySelectorAll('[data-difficulty]').forEach(x=>x.classList.toggle('selected',x===b));});
$('#startMatch').onclick=()=>start('match');$('#startPractice').onclick=()=>start('practice');$('#restartButton').onclick=restart;$('#overlayRestart').onclick=restart;$('#mainMenuButton').onclick=()=>{gameState=GAME.MENU;ui.match.classList.add('hidden');ui.refPanel.classList.add('hidden');ui.menu.classList.remove('hidden');resetScores();setRefereeState(REFEREE_STATES.IDLE);};$('#soundButton').onclick=()=>{soundOn=!soundOn;$('#soundButton').textContent=`SOUND ${soundOn?'ON':'OFF'}`;};
document.querySelectorAll('.how-to-play-button').forEach(button=>button.addEventListener('click',openHowToPlay));
$('#closeHowToPlay').onclick=closeHowToPlay;$('#closeHowToPlayX').onclick=closeHowToPlay;
$('#howToPlayModal').addEventListener('click',event=>{if(event.target.id==='howToPlayModal')closeHowToPlay();});
addEventListener('keydown',event=>{if(event.code==='Escape'&&!$('#howToPlayModal').classList.contains('hidden')){event.preventDefault();closeHowToPlay();}});
requestAnimationFrame(loop);
